(function() {var implementors = {};
implementors["rusqbin"] = ["impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/sys_common/poison/struct.PoisonError.html\" title=\"struct std::sys_common::poison::PoisonError\">PoisonError</a>&lt;T&gt;&gt; for <a class=\"enum\" href=\"rusqbin/errors/enum.Error.html\" title=\"enum rusqbin::errors::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/serde_json/1.0.2/serde_json/error/struct.Error.html\" title=\"struct serde_json::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"rusqbin/errors/enum.Error.html\" title=\"enum rusqbin::errors::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"rusqbin/errors/enum.Error.html\" title=\"enum rusqbin::errors::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;Error&gt; for <a class=\"enum\" href=\"rusqbin/errors/enum.Error.html\" title=\"enum rusqbin::errors::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://docs.rs/url/1.5.1/url/parser/enum.ParseError.html\" title=\"enum url::parser::ParseError\">ParseError</a>&gt; for <a class=\"enum\" href=\"rusqbin/errors/enum.Error.html\" title=\"enum rusqbin::errors::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://docs.rs/hyper/0.11.2/hyper/error/enum.Error.html\" title=\"enum hyper::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"rusqbin/errors/enum.Error.html\" title=\"enum rusqbin::errors::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/net/parser/struct.AddrParseError.html\" title=\"struct std::net::parser::AddrParseError\">AddrParseError</a>&gt; for <a class=\"enum\" href=\"rusqbin/errors/enum.Error.html\" title=\"enum rusqbin::errors::Error\">Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
